# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "fannie/legacy/*"
- "fannie/src/javascript/*"
- "fannie/src/fpdf/*"
- "fannie/src/Excel/*"
- "fannie/modules/plugins2.0/CoopDealsSigns/noauto/fonts/*"
- "tests/*"
